### ISSUE TITLE
[Rust] Failed to build under Linux

### ISSUE THREAD

**Issue by H0bb1t** [eshard/obfuscator-llvm#11]
Good afternoon. 
I followed the manual for [rust](https://github.com/eshard/obfuscator-llvm/wiki/Rust-obfuscation-guide) and ran into a problem building obfuscate-llvm. There were no deviations from the manual until `make -j8` command in `3. Build the obufscation` section. I've tried both branches, nothing changed.
##### Environment information:
- Arch: x86_64
- OS: Debian 11 (Docker)
- Rustup: 1.26.0
- Rust: 1.69.0

Error log in the attached file.

I would be extremely grateful for any help, as extremely interested in using this project.
Thank you in advance!
[log.txt](https://github.com/eshard/obfuscator-llvm/files/11443764/log.txt)

**Comment by PatriceBlin** [comment]
Hi,

Maybe few changes on LLVM 15.x caused this.
I though I checked the compilation against LLVM 15 when it released but now I'm not too sure anymore.
I will rebuild and check.

**Comment by PatriceBlin** [comment]
Hi,

I fixed the build against LLVM 15 and 16

You can check the branch [fix-build-llvm-15-16](/eshard/obfuscator-llvm/compare/fix-build-llvm-15-16)
We still have to test it against our usual tests to check nothing is broken.

The errors you had were linked to [LLVM enforcing C++17](https://reviews.llvm.org/D130689) starting LLVM 16.
Rust usually build against the bleeding edge of  LLVM (even if your logs says LLVM 15.0.7-rust-dev)

**Comment by H0bb1t** [comment]
Hello. 
This time I didn't encounter any problems, at least until I tried to compile my project. But these are related to the custom toolchain, so I belive we can close this issue.

Thank you very much!
